# Generated by Django 5.1.1 on 2024-12-14 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='App',
            new_name='AppDetails',
        ),
    ]
