# Generated by Django 5.1.1 on 2024-12-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_app_appdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appdetails',
            name='version',
            field=models.CharField(max_length=20),
        ),
    ]
